### ISSUE TITLE
Create socket server

### ISSUE THREAD

**Issue by Shiplayer** [Shiplayer/MentorWay#12]
- [x] Написать сокет сервер, к которому могут подключится более 1 человека одновременно.
- [x] Каждому пользователю должно отправляться сообщение каждый 10 секунд
- [x] Сообщение должно браться из заранее подготовленного файла (сперва сделать на простой тестовой фразе)

**Comment by andrey545454** [comment]
https://github.com/andrey545454/PyServer

**Comment by Shiplayer** [comment]
Написать клиент, который будет по запуску (в ручную) получать новости используя апи от [NewsApi](https://newsapi.org/).

Необходимо получить следующие новости (логическое операция "И"): 
- они должны быть из категории business
- за сегодняшний день
- популярные

Полученные новости необходимо сохранить в файл, как json объект.

**Comment by Shiplayer** [comment]
популярные новости по данной категории не требуется, достаточно получить новости за сегодняшний день и из категории business
