### ISSUE TITLE
Задача на вычисление

### ISSUE THREAD

**Issue by Shiplayer** [Shiplayer/MentorWay#19]
Сколько чисел можно представить из 512 бит?

**Comment by YorkIsMine** [comment]
https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%B9%D1%82 первые пару предложений 
а байте можно записать 2^8 чисел. Известно, что в байте 8 бит, поэтому в бите можно записать только 2 числа. Битов 512. Следовательно, ответ 2^512

**Comment by Shiplayer** [comment]
[Формула Хартли](https://ru.wikipedia.org/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D0%B0_%D0%A5%D0%B0%D1%80%D1%82%D0%BB%D0%B8). Рекомендую ее прочитать, она несет намного больше полезной информации.
