### ISSUE TITLE
Сумма по файла 

### ISSUE THREAD

**Issue by Shiplayer** [Shiplayer/MentorWay#2]
Необходимо посчитать сумму чисел из файлов. В каждом файле может быть любое количество числе, которые необходимо будет сложить.

Данные числа могут быть разделены пробелом и последовательность чисел может быть записана в несколько строк.

Необходимо вывести сумму чисел по файлу и итоговую сумму по всем файлам. Необходимо использовать многопоточность.

**Comment by Shiplayer** [comment]
написать сюда замечания

**Comment by YorkIsMine** [comment]
Замечания заключаются в том, что:
1. Надо назвать правильно классы
2. Должна быть работа с структурами данных

**Comment by YorkIsMine** [comment]
[ссылка](https://github.com/YorkIsMine/FilePac/tree/master/src/correct_filepac) на решение
