### ISSUE TITLE
Решить задачу по смещению в массиве нулей вправо

### ISSUE THREAD

**Issue by YorkIsMine** [Shiplayer/MentorWay#4]
Eсть какой-то массив (например [1,2,3,0,5,0,4]). Сделать так, чтобы все нули были в конце, при этом порядок чисел, отличных от нуля должны сохранять свой порядок(1,2,3,5,4 ,0,0]). 

Писать здесь:
https://code.yandex-team.ru/fbed0a39-f093-4d14-9598-f12c4f398c67

**Comment by Shiplayer** [comment]
Предлагаю воспользоваться двойным указателем для решения данной задачи.

**Comment by Shiplayer** [comment]
закрыл из-за неактуальности
