### ISSUE TITLE
Рефакторинг проекта GraphQL

### ISSUE THREAD

**Issue by YorkIsMine** [Shiplayer/MentorWay#5]
Выполнить рефакторинг проекта GraphQL

**Comment by Shiplayer** [comment]
ссылку на проект

**Comment by YorkIsMine** [comment]
https://github.com/YorkIsMine/GraphQL

**Comment by Shiplayer** [comment]
а какой смысл несет данный проект? Изначальная задача была потыкаться в GraphQL и все же?
