### ISSUE TITLE
NewsList Project

### ISSUE THREAD

**Issue by YorkIsMine** [Shiplayer/MentorWay#9]
Модифицировать NewsList, используя навороченные штучки а-ля RxJava2

**Comment by Shiplayer** [comment]
ссылка на [проект](https://github.com/YorkIsMine/NewsList)

**Comment by Shiplayer** [comment]
В твоем проекте будет реализована кэширование новостей и тебе надо реализовать считывание их из файла и объединить их с текущими новостями. 
Файл и путь к нему опишу позже

**Comment by Shiplayer** [comment]
- [x] Узнать способ, как получить папку, куда можно будет сохранить для кеширования данных
- [ ] Получать русские новости через 2 секунды, а американские через 5 секунд
- [x] Реализовать получение данных из кеша
- [x] Сразу же отображать новости из кеша, после мержить с новыми данными

**Comment by Shiplayer** [comment]
- [x] Сделать ViewModel вместо Presenter
